"""Phase 10C Team and Project Models

Revision ID: 0ade62379a0b
Revises: 5f87777134c3
Create Date: 2026-06-24 10:51:13.849958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ade62379a0b'
down_revision: Union[str, Sequence[str], None] = '5f87777134c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_tenant_id'), 'teams', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_teams_workspace_id'), 'teams', ['workspace_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_project_id'), 'meetings', ['project_id'], unique=False)
    op.create_index(op.f('ix_meetings_tenant_id'), 'meetings', ['tenant_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_documents_id'), 'project_documents', ['id'], unique=False)
    op.create_index(op.f('ix_project_documents_project_id'), 'project_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_documents_tenant_id'), 'project_documents', ['tenant_id'], unique=False)
    op.create_table('project_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_teams_id'), 'project_teams', ['id'], unique=False)
    op.create_index(op.f('ix_project_teams_project_id'), 'project_teams', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_teams_team_id'), 'project_teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_project_teams_tenant_id'), 'project_teams', ['tenant_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_tenant_id'), 'team_members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('ai_meeting_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_meeting_summaries_id'), 'ai_meeting_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_ai_meeting_summaries_meeting_id'), 'ai_meeting_summaries', ['meeting_id'], unique=True)
    op.create_index(op.f('ix_ai_meeting_summaries_tenant_id'), 'ai_meeting_summaries', ['tenant_id'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_attendees_id'), 'meeting_attendees', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_meeting_id'), 'meeting_attendees', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_tenant_id'), 'meeting_attendees', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_user_id'), 'meeting_attendees', ['user_id'], unique=False)
    op.create_table('meeting_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_notes_id'), 'meeting_notes', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_notes_meeting_id'), 'meeting_notes', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_notes_tenant_id'), 'meeting_notes', ['tenant_id'], unique=False)
    op.add_column('channels', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_channels_project_id'), 'channels', ['project_id'], unique=False)
    op.create_foreign_key(None, 'channels', 'projects', ['project_id'], ['id'])
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_column('tasks', 'team_id')
    op.drop_column('tasks', 'project_id')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_index(op.f('ix_channels_project_id'), table_name='channels')
    op.drop_column('channels', 'project_id')
    op.drop_index(op.f('ix_meeting_notes_tenant_id'), table_name='meeting_notes')
    op.drop_index(op.f('ix_meeting_notes_meeting_id'), table_name='meeting_notes')
    op.drop_index(op.f('ix_meeting_notes_id'), table_name='meeting_notes')
    op.drop_table('meeting_notes')
    op.drop_index(op.f('ix_meeting_attendees_user_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_tenant_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_meeting_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_id'), table_name='meeting_attendees')
    op.drop_table('meeting_attendees')
    op.drop_index(op.f('ix_ai_meeting_summaries_tenant_id'), table_name='ai_meeting_summaries')
    op.drop_index(op.f('ix_ai_meeting_summaries_meeting_id'), table_name='ai_meeting_summaries')
    op.drop_index(op.f('ix_ai_meeting_summaries_id'), table_name='ai_meeting_summaries')
    op.drop_table('ai_meeting_summaries')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_tenant_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_project_teams_tenant_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_team_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_project_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_id'), table_name='project_teams')
    op.drop_table('project_teams')
    op.drop_index(op.f('ix_project_documents_tenant_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_project_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_id'), table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_meetings_tenant_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_project_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_teams_workspace_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_tenant_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
