"""phase 10b workspace messages and documents

Revision ID: 5f87777134c3
Revises: e938746a579f
Create Date: 2026-06-11 21:03:04.498065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f87777134c3'
down_revision: Union[str, Sequence[str], None] = 'e938746a579f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_messages_id'), 'workspace_messages', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_messages_tenant_id'), 'workspace_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workspace_messages_workspace_id'), 'workspace_messages', ['workspace_id'], unique=False)
    op.create_table('channel_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_messages_channel_id'), 'channel_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_id'), 'channel_messages', ['id'], unique=False)
    op.create_index(op.f('ix_channel_messages_tenant_id'), 'channel_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_workspace_id'), 'channel_messages', ['workspace_id'], unique=False)
    op.create_table('approval_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_documents_approval_id'), 'approval_documents', ['approval_id'], unique=False)
    op.create_index(op.f('ix_approval_documents_id'), 'approval_documents', ['id'], unique=False)
    op.create_index(op.f('ix_approval_documents_tenant_id'), 'approval_documents', ['tenant_id'], unique=False)
    op.create_table('task_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_documents_id'), 'task_documents', ['id'], unique=False)
    op.create_index(op.f('ix_task_documents_task_id'), 'task_documents', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_documents_tenant_id'), 'task_documents', ['tenant_id'], unique=False)
    op.add_column('approvals', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('approvals', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('approvals', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_approvals_channel_id'), 'approvals', ['channel_id'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_approvals_workspace_id'), 'approvals', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'approvals', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'approvals', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key(None, 'approvals', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('tasks', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_channel_id'), 'tasks', ['channel_id'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_workspace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_channel_id'), table_name='tasks')
    op.drop_column('tasks', 'channel_id')
    op.drop_column('tasks', 'workspace_id')
    op.drop_column('tasks', 'tenant_id')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_index(op.f('ix_approvals_workspace_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_channel_id'), table_name='approvals')
    op.drop_column('approvals', 'channel_id')
    op.drop_column('approvals', 'workspace_id')
    op.drop_column('approvals', 'tenant_id')
    op.drop_index(op.f('ix_task_documents_tenant_id'), table_name='task_documents')
    op.drop_index(op.f('ix_task_documents_task_id'), table_name='task_documents')
    op.drop_index(op.f('ix_task_documents_id'), table_name='task_documents')
    op.drop_table('task_documents')
    op.drop_index(op.f('ix_approval_documents_tenant_id'), table_name='approval_documents')
    op.drop_index(op.f('ix_approval_documents_id'), table_name='approval_documents')
    op.drop_index(op.f('ix_approval_documents_approval_id'), table_name='approval_documents')
    op.drop_table('approval_documents')
    op.drop_index(op.f('ix_channel_messages_workspace_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_tenant_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_channel_id'), table_name='channel_messages')
    op.drop_table('channel_messages')
    op.drop_index(op.f('ix_workspace_messages_workspace_id'), table_name='workspace_messages')
    op.drop_index(op.f('ix_workspace_messages_tenant_id'), table_name='workspace_messages')
    op.drop_index(op.f('ix_workspace_messages_id'), table_name='workspace_messages')
    op.drop_table('workspace_messages')
    # ### end Alembic commands ###
