"""phase 9 sla and governance models

Revision ID: ffdd018ce291
Revises: 
Create Date: 2026-05-26 15:58:52.416537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdd018ce291'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegator_id', sa.Integer(), nullable=True),
    sa.Column('delegatee_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegatee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_delegations_id'), 'approval_delegations', ['id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('task_notifications', sa.Boolean(), nullable=True),
    sa.Column('approval_notifications', sa.Boolean(), nullable=True),
    sa.Column('escalation_notifications', sa.Boolean(), nullable=True),
    sa.Column('document_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('sla_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('allowed_hours', sa.Integer(), nullable=True),
    sa.Column('escalation_enabled', sa.Boolean(), nullable=True),
    sa.Column('escalation_after_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_rules_id'), 'sla_rules', ['id'], unique=False)
    op.create_index(op.f('ix_sla_rules_module_name'), 'sla_rules', ['module_name'], unique=False)
    op.create_table('approval_escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('escalated_from', sa.Integer(), nullable=True),
    sa.Column('escalated_to', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['escalated_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_escalations_id'), 'approval_escalations', ['id'], unique=False)
    op.create_table('sla_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('sla_rule_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('due_time', sa.DateTime(), nullable=True),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('breach_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sla_rule_id'], ['sla_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_tracking_id'), 'sla_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_sla_tracking_module_name'), 'sla_tracking', ['module_name'], unique=False)
    op.create_index(op.f('ix_sla_tracking_record_id'), 'sla_tracking', ['record_id'], unique=False)
    op.create_index(op.f('ix_approval_history_approval_id'), 'approval_history', ['approval_id'], unique=False)
    op.add_column('approvals', sa.Column('sla_status', sa.String(length=50), nullable=True))
    op.add_column('approvals', sa.Column('sla_due_time', sa.DateTime(), nullable=True))
    op.add_column('approvals', sa.Column('is_escalated', sa.Boolean(), nullable=True))
    op.add_column('approvals', sa.Column('current_escalation_to', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_foreign_key(None, 'approvals', 'users', ['current_escalation_to'], ['id'])
    op.add_column('audit_logs', sa.Column('module_name', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('action_type', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('old_data', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_data', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_documents_task_id'), 'documents', ['task_id'], unique=False)
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('priority', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('sla_status', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('sla_due_time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('is_sla_breached', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_column('tasks', 'is_sla_breached')
    op.drop_column('tasks', 'sla_due_time')
    op.drop_column('tasks', 'sla_status')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'notification_type')
    op.drop_index(op.f('ix_documents_task_id'), table_name='documents')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'new_data')
    op.drop_column('audit_logs', 'old_data')
    op.drop_column('audit_logs', 'action_type')
    op.drop_column('audit_logs', 'module_name')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_column('approvals', 'current_escalation_to')
    op.drop_column('approvals', 'is_escalated')
    op.drop_column('approvals', 'sla_due_time')
    op.drop_column('approvals', 'sla_status')
    op.drop_index(op.f('ix_approval_history_approval_id'), table_name='approval_history')
    op.drop_index(op.f('ix_sla_tracking_record_id'), table_name='sla_tracking')
    op.drop_index(op.f('ix_sla_tracking_module_name'), table_name='sla_tracking')
    op.drop_index(op.f('ix_sla_tracking_id'), table_name='sla_tracking')
    op.drop_table('sla_tracking')
    op.drop_index(op.f('ix_approval_escalations_id'), table_name='approval_escalations')
    op.drop_table('approval_escalations')
    op.drop_index(op.f('ix_sla_rules_module_name'), table_name='sla_rules')
    op.drop_index(op.f('ix_sla_rules_id'), table_name='sla_rules')
    op.drop_table('sla_rules')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_approval_delegations_id'), table_name='approval_delegations')
    op.drop_table('approval_delegations')
    # ### end Alembic commands ###
